#!/bin/bash

echo ""
echo "##########################################"
echo "##         SECONDRUN INIT SCRIPT        ##"
echo "## WAIT SOME MINUTES FOR CONFIGURATIONS ##"
echo "##########################################"
echo ""
echo "##############################"
echo "# Expanding rootfs partition #"
echo "##############################"
echo ""
/sbin/resize2fs /dev/mmcblk0p1
/bin/systemctl disable secondrun
touch /etc/yunohost/cube_installed

exit 0
